export const GET_PROPERTIES_FAILURE='GET_PROPERTIES_FAILURE'
export const GET_PROPERTIES_SUCCESS='GET_PROPERTIES_SUCCESS'

// export const GET_LISTING_FAILURE='GET_LISTINGS_FAILURE'
// export const GET_LISTING_SUCCESS='GET_LISTINGS_SUCCESS'