export const GET_FETCH_FAILURE='GET_FETCH_FAILURE'

export const GET_PROPERTIES_SUCCESS='GET_PROPERTIES_SUCCESS'
// export const GET_LISTING_SUCCESS='GET_LISTING_SUCCESS'
export const GET_WEATHER_SUCCESS='GET_WEATHER_SUCCESS'
export const GET_EVENTS_SUCCESS='GET_EVENTS_SUCCESS'
export const GET_HOLIDAY_SUCCESS='GET_HOLIDAY_SUCCESS'